// <auto-generated />
using System;
using BlazorCrud.Server.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlazorCrud.Server.Migrations
{
    [DbContext(typeof(DbcrudTContext))]
    [Migration("20240424184034_AddColumnIdEmpleadoOnEmpleado")]
    partial class AddColumnIdEmpleadoOnEmpleado
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BlazorCrud.Server.Models.Departamento", b =>
                {
                    b.Property<int>("IdDepartamento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idDepartamento");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDepartamento"));

                    b.Property<string>("Nombre")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nombre");

                    b.HasKey("IdDepartamento")
                        .HasName("PK__departam__C225F98D21C47132");

                    b.ToTable("departamento", (string)null);
                });

            modelBuilder.Entity("BlazorCrud.Server.Models.Empleado", b =>
                {
                    b.Property<int>("IdEmpleado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEmpleado"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateOnly>("FechaInicio")
                        .HasColumnType("date");

                    b.Property<int?>("IdDepartamentoNavigationIdDepartamento")
                        .HasColumnType("int");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdEmpleado");

                    b.HasIndex("IdDepartamentoNavigationIdDepartamento");

                    b.ToTable("Empleado", (string)null);
                });

            modelBuilder.Entity("BlazorCrud.Server.Models.Persona", b =>
                {
                    b.Property<int>("IdPersona")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idPersona");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPersona"));

                    b.Property<DateOnly?>("FechaContrato")
                        .HasColumnType("date")
                        .HasColumnName("fechaContrato");

                    b.Property<int?>("IdDepartamento")
                        .HasColumnType("int")
                        .HasColumnName("idDepartamento");

                    b.Property<string>("NombreCompleto")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nombreCompleto");

                    b.Property<int?>("Sueldo")
                        .HasColumnType("int")
                        .HasColumnName("sueldo");

                    b.HasKey("IdPersona")
                        .HasName("PK__persona__A47881413623E1E7");

                    b.HasIndex("IdDepartamento");

                    b.ToTable("persona", (string)null);
                });

            modelBuilder.Entity("BlazorCrud.Server.Models.Empleado", b =>
                {
                    b.HasOne("BlazorCrud.Server.Models.Departamento", "IdDepartamentoNavigation")
                        .WithMany()
                        .HasForeignKey("IdDepartamentoNavigationIdDepartamento");

                    b.Navigation("IdDepartamentoNavigation");
                });

            modelBuilder.Entity("BlazorCrud.Server.Models.Persona", b =>
                {
                    b.HasOne("BlazorCrud.Server.Models.Departamento", "IdDepartamentoNavigation")
                        .WithMany("Personas")
                        .HasForeignKey("IdDepartamento")
                        .HasConstraintName("FK__persona__idDepar__25869641");

                    b.Navigation("IdDepartamentoNavigation");
                });

            modelBuilder.Entity("BlazorCrud.Server.Models.Departamento", b =>
                {
                    b.Navigation("Personas");
                });
#pragma warning restore 612, 618
        }
    }
}
